### ISSUE TITLE
add a contributing file

### ISSUE THREAD

**Issue by MohammedHamzaMalik** [MohammedHamzaMalik/100-Days-of-JavaScript-Code#1]
Add a contributing file in markdown format which describes how to contribute to this repository.
Also mention the issue in the description of the PR

**Comment by oneamanish** [comment]
see my pull req.

**Comment by MohammedHamzaMalik** [comment]
Hello @oneamanish , your contribute.md file is very much simple and this issue is already resolved.
If you want to work on this issue you can modify the already existing conrtibuting file.
